### ISSUE TITLE
CSS class has been removed

### ISSUE THREAD

**Issue by heyanctil** [DanielYKPan/date-time-picker#33]
I've started working with this datetime picker in our project and yesterday when I've installed the latest version, some override of CSS that I've made stop working. I see that some class like «out-focus» has been remove and there is no selector anymore that I can use to apply my customization. Is it something that you can fix, or I need to use previous version (4.0.5?).

I did that customization to works with Angular Material 2 and it supports theme:
![image](https://cloud.githubusercontent.com/assets/7291291/25181744/881c4f28-24e0-11e7-9ba0-e7d7459b2fdb.png)

**Comment by DanielYKPan** [comment]
@heyanctil 

You could customize the color with [theme] options

**Comment by heyanctil** [comment]
Hmm I don't think it's the best way. We are currently building a toolkit and we support themes globally accross the platform. I don't think setting a property somewhere for the datepicker is the right solution for us... Right now, we use the version 4.0.5, and the capabilities to override classes is perfect for our needs!

**Comment by DanielYKPan** [comment]
@heyanctil 
What classes are u using? just out-focus?

**Comment by heyanctil** [comment]
I didn't push the investigation further when I saw that there was breaking changes with latest version. «.today» &  «.action-today» have moved but It's not a big deal.

This is a copy of my Sass file I did to support theming with your control:
```css
@mixin datetime-picker($theme) {
  .datetime-picker {
    .mat-input-wrapper {
      .mdi {
        color: map-get($theme, text-icon);
      }

      input {
        color: map-get($theme, text-icon);
      }

      date-time-dialog {
        .picker-dropdown {
          .picker-box {
            .picker-banner {
              background-color: map-get($theme, accent-color) !important;
            }

            .picker-content {
              background-color: map-get($theme, primary-color);
              border-left: solid 1px map-get($theme, accent-color);
              border-right: solid 1px map-get($theme, accent-color);
              border-bottom: solid 1px map-get($theme, accent-color);

              .picker-control-nav {
                .nav-prev:before, .nav-next:before {
                  border-left-color: map-get($theme, text-icon);
                  border-right-color: map-get($theme, text-icon);
                }
              }

              .month {
                color: map-get($theme, text-icon);
              }

              .picker-day {
                color: map-get($theme, text-icon);

                &.out-focus {
                  @if map-get($theme, style) == dark {
                    color: darken(map-get($theme, text-icon), 15%);
                  } @else if map-get($theme, style) == light {
                    color: lighten(map-get($theme, text-icon), 50%);
                  }
                }

                &.selected {
                  color: #fff;
                  background: map-get($theme, accent-color);
                }

                /*.today-icon {
                  border-top-color: map-get($theme, accent-color) !important;
                }*/

              }

              .picker-day:hover {
                background: lighten(map-get($theme, accent-color), 10%);
                color: #fff;
              }

              .picker-month {
                color: map-get($theme, text-icon);

                &.selected {
                  color: #fff;
                  background: map-get($theme, accent-color);
                }
              }

              .picker-year {
                color: map-get($theme, text-icon);

                &.selected {
                  color: #fff;
                  background: map-get($theme, accent-color);
                }
              }

              .today:before {
                border-top-color: map-get($theme, accent-color);
              }

              .action-today:before {
                border-top-color: map-get($theme, accent-color);
              }

              .picker-action {
                color: map-get($theme, text-icon);

                /*.today-icon {
                  border-top-color: map-get($theme, accent-color) !important;
                }*/

              }
            }
          }
        }

        .time-panel {
          .time-panel-header {
            .time {
              color: map-get($theme, accent-color);
            }
          }

          .time-control {
            .title {
              color: map-get($theme, text-icon);
            }

            app-slide-bar {
              .bar {
                .highlight {
                  background: map-get($theme, accent-color);
                }
              }
            }
          }

          .control {
            .button {
              background: map-get($theme, accent-color);
              border-color: map-get($theme, accent-color);
            }
          }
        }
      }
    }
  }

}
```
